version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/open-toolchain/secure-kube-toolchain](https://github.com/open-toolchain/secure-kube-toolchain)
    git branch: >-
      [master](https://github.com/open-toolchain/secure-kube-toolchain/tree/master)
toolchain:
  name: 'kube-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    $switch:
      - $expr: $env.source_provider
      - $default: 'hostedgit'
        service_id: hostedgit
        parameters:
          repo_name: 'hello-containers-{{timestamp}}'
          repo_url: "$env.type === 'link' ? $env.app_repo : 'https://github.com/open-toolchain/hello-containers'"
          source_repo_url: "$env.type === 'fork' || $env.type === 'clone' ? $env.app_repo : ''"
          type: $env.type || 'clone'
          has_issues: true
          enable_traceability: true
      - $case: 'githubconsolidated'
        service_id: githubconsolidated
        parameters:
          repo_name: 'hello-containers-{{timestamp}}'
          repo_url: "$env.type === 'link' ? $env.app_repo : 'https://github.com/open-toolchain/hello-containers'"
          source_repo_url: "$env.type === 'fork' || $env.type === 'clone' ? $env.app_repo : ''"
          type: $env.type  || 'clone'
          visibility: public
      - $case: 'github_integrated'
        service_id: github_integrated
        parameters:
          repo_name: 'hello-containers-{{timestamp}}'
          repo_url: "$env.type === 'link' ? $env.app_repo : 'https://github.com/open-toolchain/hello-containers'"
          source_repo_url: "$env.type === 'fork' || $env.type === 'clone' ? $env.app_repo : ''"
          type: "$env.type !== undefined ? $env.type : 'clone'"
          has_issues: true
          enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
  pr_build:
    $switch:
      - $expr: $env.enablePrPipeline
      - $default: 'false'
      - $case: 'true'
        service_id: pipeline
        name: 'PullRequest'
        ui-pipeline: true
        configuration:
          content:
            $text: pipelinePR.yml
          env:
            GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
